# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIDemos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIDemos

  pod 'Masonry'
#  pod 'MTHawkeye'
  pod 'FLEX'
  pod 'FBRetainCycleDetector'

  target 'UIDemosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIDemosUITests' do
    # Pods for testing
  end

end
